apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::201462388357:role/jenkins-ec2-role
      username: jenkins
      groups:
        - system:masters
